### ISSUE TITLE
Voting seeds should not be generated for planets and stars

### ISSUE THREAD

**Issue by gavinpatkinson** [urbit/keygen-js#16]
Currently planets and stars have voting seeds generated for them despite not having this capability.

FYI delegate seeds are now called votings seeds per https://github.com/urbit/keygen-js/issues/14

**Comment by jtobin** [comment]
I.e. for planet and star *wallets*?  There are no per-ship voting seeds implemented here at present, unless I've misunderstood something.

From the changes in urbit/constitution#23, I think the implementation here might actually have to be changed anyway, though.  I'll take a look in more detail.
