### ISSUE TITLE
TypeError: Cannot read property 'utils' of undefined

### ISSUE THREAD

**Issue by gavinpatkinson** [urbit/keygen-js#3]
Branch: `tests`

Encountered when running against tests against dist/bundle.js
This also appears in the wallet-generator frontend.

I think this has something to do with the BIP32 library, or how this specific part is bundled.
```
TypeError: Cannot read property 'utils' of undefined

      14015 | 
      14016 | 
    > 14017 | var utils$1 = elliptic_1.utils;
            |                          ^
      14018 | var getNAF = utils$1.getNAF;
      14019 | var getJSF = utils$1.getJSF;
      14020 | var assert$2 = utils$1.assert;

      at Object.utils (dist/index.js:14017:26)
      at Object.<anonymous> (tests/test.js:1:1)
```

**Comment by gavinpatkinson** [comment]
@joemfb do you have time to take a look at this? Seems to be the final issue blocking this lib from being bundled.

**Comment by joemfb** [comment]
I'm happy to, but I'm not clear on the bundling requirements for this lib. Won't any downstream applications have to include their own bundling regardless of what's done here?

**Comment by gavinpatkinson** [comment]
keygen-js should just be an common js module. The bundling step completes, but using the lib returns this error.

**Comment by gavinpatkinson** [comment]
@joemfb you seriously rock dude. Thanks for the help! Closing.

**Comment by seansean11** [comment]
Was this resolved?  I'm running into the same issue when using this package with rollup.

**Comment by jtobin** [comment]
@seansean11 IIRC you can try the `rollup-plugin-node-resolve` plugin and specify the following in your `rollup.config.js` or similar:

``` javascript
plugins: [
  ..,
  resolve({
    browser: true,
  }),
  ..
]
```
