### ISSUE TITLE
Should use latest argon2-wasm using NPM

### ISSUE THREAD

**Issue by Fang-** [urbit/keygen-js#53]
Currently, we just point to a (now-outdated) commit on [urbit/argon2-wasm](https://github.com/urbit/argon2-wasm). This is stupid and needs to be done more cleanly.

Steps to do this:
- Publish the latest Argon2-wasm up as an NPM module
- Update keygen-js' Argon2-wasm entry in `package.json` to point to the NPM package
- Update and rebuild keygen-js

**Comment by jtobin** [comment]
Resolved by #54.
