### ISSUE TITLE
Update to Azimuth nomenclature

### ISSUE THREAD

**Issue by jtobin** [urbit/keygen-js#57]
Ship -> point, etc.

**Comment by Fang-** [comment]
Probably not? This is about *Urbit* key generation, and Urbit deals with *ships*. Points are an Azimuth thing, and while they lie at the foundation of Urbit ships, they are not the surface.

**Comment by Fang-** [comment]
There is, of course, an argument to be made about turning this and our spec into being about Azimuth wallets, but I'd counter that by saying that different applications of Azimuth have different requirements as far as wallets are concerned.

**Comment by jtobin** [comment]
Hard to say.  I'd argue that in the general case one is generating a wallet for an Azimuth point, not specifically a ship (which, as you state correctly, is an Arvo-level concept).

But perhaps you're right.  My main concern is that the switching of nomenclature from 'point' to 'ship' in Bridge for keygen arguments alone feels weird. 😄

**Comment by Fang-** [comment]
Bridge is an Urbit tool for dealing with Urbit assets, and so should already be talking about ships rather than points. Exception there is, of course, the azimuth-js interfacing.

**Comment by jtobin** [comment]
**eyes cutlass**

**Comment by jtobin** [comment]
This one doesn't seem necessary, and hasn't gone anywhere, so let's shut 'er down.
