### ISSUE TITLE
Bundling with Parcel fails

### ISSUE THREAD

**Issue by shrugs** [urbit/keygen-js#62]
When bundling within a Parcel/typescript project, the isomorphic-crypto import is actually under `crypto.default`, not the top-level `crypto` import, so references to it return undefined. I expect this is because it treats the dependency as a [modern es6 module](https://github.com/kevlened/isomorphic-webcrypto/blob/master/package.json#L6) rather than a commonjs require (or something like that, i don't really understand JS anyway).

Anyway, importing the `urbit-key-generation/dist` is a fine stopgap for now.

**Comment by jtobin** [comment]
`isomorphic-webcrypto` is a weird dependency that's really only in our library for legacy reasons.  Its SHA-256 implementation is asynchronous for some reason, which never sat well with me.

I pushed up [a branch](https://github.com/urbit/keygen-js/tree/jt-issue-62) that axes `isomorphic-webcrypto` and replaces it with `js-sha256`.  Want to try using it with your Parcel build and see if it works any better?

(I'll probably wind up merging this in anyway, as the latter library seems superior here.)

**Comment by shrugs** [comment]
Confirmed working on my end (and feels faster, just maybe?). Check it out at https://github.com/shrugs/azid / https://azid.shrugs.now.sh

**Comment by jtobin** [comment]
Sweet, I'll merge it in and push a release.  And your project looks great!
